joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


#ここからros_controllerで扱う　関節を追加する

#joint名_position_controller:
#type: position_controllers/JointPositionController
  #joint: モデル内で定義されている名
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - c_head_yaw
    - l_shouluder_pitch    
    - l_shouluder_roll
    - l_elbow_yaw
    - l_elbow_pitch
     - r_shouluder_pitch
     - r_shouluder_roll
     - r_elbow_yaw
     - r_elbow_pitch
    - l_hipjoint_yaw
    - l_hipjoint_roll
    - l_hipjoint_pitch
    - l_knee_pitch
    - l_ankle_pitch
    - l_ankle_roll
     - r_hipjoint_yaw
     - r_hipjoint_roll
     - r_hipjoint_pitch
     - r_knee_pitch
     - r_ankle_pitch
     - r_ankle_roll
